excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ThoughtNoise.github.io
title: ThoughtNoise
tagline: A place to collect project ideas
description: My awesome new site
paginate: 5